"use server";

import { auth } from "@clerk/nextjs/server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createServiceClient } from "@/lib/supabase";
import { getTenantAccountRole, getTenantById } from "@/lib/tenant";

// ── Guards ─────────────────────────────────────────────────────────────────────

async function requireTenantAdmin(tenantId: string) {
  const { userId } = await auth();
  if (!userId) throw new Error("Unauthorized");
  const role = await getTenantAccountRole(tenantId, userId);
  if (role !== "tenant_admin") throw new Error("Forbidden");
  return userId;
}

// ── Provision new account via invite ──────────────────────────────────────────

export async function provisionAccount(formData: FormData) {
  const tenantId = formData.get("tenantId") as string;
  const email = formData.get("email") as string;
  const role = (formData.get("role") as string) || "member";

  await requireTenantAdmin(tenantId);

  const tenant = await getTenantById(tenantId);
  if (!tenant) throw new Error("Tenant not found");

  // Enforce seat limit before creating invite
  const db = createServiceClient();
  const { data: accounts } = await db
    .from("tenant_accounts")
    .select("seat_count")
    .eq("tenant_id", tenantId)
    .eq("status", "active");

  const totalSeats = (accounts ?? []).reduce((s, a) => s + (a.seat_count ?? 1), 0);
  if (totalSeats >= tenant.pricing.max_seats) {
    throw new Error(`Seat limit reached (${tenant.pricing.max_seats} max). Contact support.`);
  }

  // Create invite record (token is auto-generated by DB default)
  const { data: invite, error } = await db
    .from("tenant_invites")
    .insert({ tenant_id: tenantId, role })
    .select("token")
    .single();

  if (error || !invite) throw new Error("Failed to create invite");

  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";
  const inviteUrl = `${appUrl}/accept-invite?token=${invite.token}&email=${encodeURIComponent(email)}`;

  // In production, send the invite via your transactional email service here,
  // passing tenant branding (app_name, logo_url, primary_color) for fully
  // branded email appearance. For now, the invite URL is returned to the admin.
  // TODO: integrate with your email provider (SendGrid, Resend, etc.)
  console.log(`Invite URL for ${email}: ${inviteUrl}`);

  revalidatePath("/tenant-admin");
  redirect(`/tenant-admin?invited=1&url=${encodeURIComponent(inviteUrl)}`);
}

// ── Suspend account ───────────────────────────────────────────────────────────

export async function suspendAccount(formData: FormData) {
  const tenantId = formData.get("tenantId") as string;
  const accountId = formData.get("accountId") as string;
  await requireTenantAdmin(tenantId);

  const db = createServiceClient();
  const { error } = await db
    .from("tenant_accounts")
    .update({ status: "suspended" })
    .eq("id", accountId)
    .eq("tenant_id", tenantId); // scope to this tenant only

  if (error) throw new Error("Failed to suspend account");

  revalidatePath("/tenant-admin");
}

// ── Remove account ────────────────────────────────────────────────────────────

export async function removeAccount(formData: FormData) {
  const tenantId = formData.get("tenantId") as string;
  const accountId = formData.get("accountId") as string;
  await requireTenantAdmin(tenantId);

  const db = createServiceClient();
  const { error } = await db
    .from("tenant_accounts")
    .update({ status: "removed" })
    .eq("id", accountId)
    .eq("tenant_id", tenantId);

  if (error) throw new Error("Failed to remove account");

  revalidatePath("/tenant-admin");
}
